services:
  devices:
    build: .
    image: "devices_jar:latest"
    restart: always
    ports: 
       - "8080:8080"
    expose:
       - "8080:8080" 
    command: sh -c "yarn install && yarn run dev"
